FROM ubuntu:latest

RUN apt-get -y update \
  && apt-get -y install \
	git \
	curl \
	wget \
	vim \
	gcc \
	make \
	rubygems \
	ruby-dev \
	fontconfig

ENV SHELL_I_HAVE_READ=Y
ENV SHELL_PACKAGE_MANAGER=apt-get
ENV SHELL_INSTALL_COLORLS=Y
ENV SHELL_CREATE_SYMLINK=Y

WORKDIR /root/config
COPY . .

ENTRYPOINT sleep infinity

